
# --------------------------
# This code is autogenerated
data = 0
while data not in [1, 2]:
    data = int(input('Which data set do you want to use? 1 = Test, 2 = Input '))
if data == 1:
    fn = 'btest'+str(1)+'.txt'
elif data == 2:
    fn = 'input'+str(1)+'.txt'
f = open(fn, 'r')
raw = [j for j in f.read().splitlines()]
# --------------------------

#%% Part 1

import re
nums = []
for r in raw:
    digList = re.findall(r'\d', r)
    nums.append(int(digList[0] + digList[-1]))
print('Part 1 Answer: '+ str(sum(nums)))

#%% Part 2

import regex
numDict = {'zero': '0', 'one': '1', 'two': '2', 'three': '3', 'four': '4', 
           'five': '5', 'six': '6', 'seven': '7', 'eight': '8', 'nine': '9'}
patt = '\d|' + '|'.join(numDict.keys())
nums = []
for r in raw:
    digList = regex.findall(patt, r, overlapped=True)
    # print(digList)
    if digList[0] in numDict.keys():
        n1 = numDict[digList[0]]
    else:
        n1 = digList[0]
    if digList[-1] in numDict.keys():
        n2 = numDict[digList[-1]]
    else:
        n2 = digList[-1]    
    nums.append(int(n1 + n2))
print('Part 2 Answer: ' + str(sum(nums)))